### ISSUE TITLE
Error uploading to board

### ISSUE THREAD

**Issue by PClough** [danthegoodman1/esp8266-deauther#1]
Hi, I have the same breakout esp8266 shown in your pictures and have followed all your instructions and tried changing the board version to the latest 2.3.0 but I keep getting the following error message:
"Arduino: 1.8.1 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, 9600, 4M (3M SPIFFS)"
Build options changed, rebuilding all
Sketch uses 518139 bytes (49%) of program storage space. Maximum is 1044464 bytes.
Global variables use 48648 bytes (59%) of dynamic memory, leaving 33272 bytes for local variables. Maximum is 81920 bytes.
Uploading 522288 bytes from C:\Users\NAME\AppData\Local\Temp\arduino_build_146076/esp8266_deauther.ino.bin to flash at 0x00000000
................................................................................ [ 15% ]
................................................................................ [ 31% ]
................................................................................ [ 46% ]
.....................An error occurred while uploading the sketch

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences."

Any help you could off would be great!

Thanks
PClough

**Comment by marqueeeeeee** [comment]
have your tried uninstalling the version 2.3 and re-installing the 2.0.0?

**Comment by PClough** [comment]
Hi, Yeah I tried that. I got it working last night by deleting esp8266_deauth library and replacing it with a new copy. No idea why this worked, but thanks anyway!

**Comment by officiallor** [comment]
@danthegoodman1 I think it should be marked as solved
