### ISSUE TITLE
Chrome cannot display the default config page

### ISSUE THREAD

**Issue by dorcusmafia** [danthegoodman1/esp8266-deauther#3]
When the "192.168.4.1" address is entered into Chrome, the following error message is shown:

ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_LENGTH

Which doesn't allow this page to be displayed, however the deauther config page still works in Edge on Windows and Safari on iOS.

**Comment by danthegoodman1** [comment]
I would ask this on the original GitHub.
